# R package release checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check-release

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) 


    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}


    env:
      R_DEFAULT_INTERNET_TIMEOUT: 300
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install texlive-latex-base libharfbuzz-dev libfribidi-dev
          sudo apt-get install gsl-bin libgsl0-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install jags

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'